config/routes.rb
Rails.application.routes.draw do
  get 'books' => 'books#index'
  post 'books' => 'books#create'
  get '/' => 'homes#top'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id/edit' => 'books#update', as: 'update_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def index
    @books = Book.all
    @book = Book.new
    @id = params[:id]
  end

  def show
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    if @book.save
     flash[:notice] = "Book was successfully created"
     redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:coment] = "Book was successfully updated."
      render :show
    else
     render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
     flash[:success] = 'Book was successfully destroyed.'
     redirect_to '/books'
    else
      lash[:success] ='Book was not successfully destroyed.'
      redirect_to '/books'
    end
  end

  private
   def book_params
     params.require(:book).permit(:title, :body)
   end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<%= form_with model: @book, url: edit_book_path(@book.id), method: :patch do |f| %>
<div class="edit_contents">
 <div class="edit_tb">
  <h2>Edditing Book</h2>
 </div>
 <% if @book.errors.any? %>
 <ul>
   <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
   <% end %>
 </ul>
<% end %>

 <p>Title</p>
 <div class="edit_tb">
  <%= f.text_field :title %>
 </div>

 <p>Body</p>
 <div class="edit_tb">
  <%= f.text_area :body %></br>
 </div>
 <%= f.submit 'Update Book' %>
 <% end %>
</div>

 <div class="edit_eb">
  <div class="edit_edit">
   <%= link_to "Edit", edit_book_path(@book.id) %>
  </div>
  <div class="edit_icon">
    <p>|</p>
  </div>
  <div class="edit_back">
   <a href="/books">Back</a>
  </div>
 </div>

app/views/books/index.html.erb
<% if flash[:success] %>
 <p class="index_destroy_message"><%= flash[:success] %></p>
<% end %>

<header class="index_header">
  <h1>Books</h1>
</header>


<div class="index_main_content">
<table>
  <tr><th>Title</th><th>Body</th></tr>
  <% @books.each do |book| %>
<div class="edit_contents">
  <tr>
    <td><%= book.title %></td>
    <td><%= book.body %></td>
    <td><%= link_to"Show", "books/#{book.id}" %></td>
    <td><%= link_to"Edit", "books/#{book.id}/edit" %></td>
    <td><%= link_to "Destroy", destroy_book_path("#{book.id}"), method: :delete, "data-confirm" => "Are you sure?" %></td>
  </tr>
  <% end %>
</table>
</div>

<div class="index_write_contet">
<h2 class="index_write_subject">New Book</h2>
<% if @book.errors.any? %>
 <ul>
   <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
   <% end %>
 </ul>
<% end %>
<%= form_with model: @book do |f| %>
<p class="index_write_title">Title</p>
<%= f.text_field :title %>
<p class="index_write_body">Body</p>
<%= f.text_area :body %></br>
<div class="index_write_submit">
<%= f.submit 'Create Book' %>
</div>
<% end %>
</div>

app/views/books/new.html.erb
<div>
<h2>New Book</h2>
<%= form_with model: @book, url: '/books', method: :post  do |f| %>
<p>title</p>
<%= f.text_field :title %>
<p>body</p>
<%= f.text_area :body %>
<%= f.submit 'Create Book' %>
<% end %>
</div>

app/views/books/show.html.erb
<div>
  <p class="show_flash_message"><%= flash[:notice] %></p>
</div>

<% if flash[:coment] %>
 <p class="show_update_message"><%= flash[:coment] %></p>
<% end %>


<div class="show_contents">
 <div class="show_tb">
  <p><a class="show_subject">Title: </a><a><%= @book.title %></a></p>
 </div>
 <div class="show_tb">
  <p><a class="show_subject">Body: </a><a><%= @book.body %></a></p>
 </div>
</div>

 <div class="show_eb">
  <div class="show_edit">
   <%= link_to "Edit", edit_book_path(@book.id) %>
  </div>
  <div class="show_icon">
    <p>|</p>
  </div>
  <div class="show_back">
   <a href="/books">Back</a>
  </div>
 </div>

app/views/homes/top.html.erb
<div class="top_title">
<h1>ようこそBookersへ！</h1>
</div>

<div class="top_detail">
<p><a class="top_subject">Bookers</a>では、さまざまな書籍に関するあなたの意見や</p>
</div>

<div class="top_detail">
<p>印象を共有し交換することができます</p>
</div>

<div class="top_detail">
<a href="/books">start</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>